# Generated by Django 5.0 on 2024-01-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='Last_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
